### ISSUE TITLE
[Feature] item pickup delay when dropped from inventory

### ISSUE THREAD

**Issue by KrAzYGEEK32** [SuperMartijn642/SimpleMagnets#11]
**Is your feature request related to a problem? Please describe.**
when an item is thrown from a player inventory onto the ground, it does respect pickup delay but still pulls the dropped item towards the player

**Describe the solution you'd like**
when an item is dropped, the magnet shouldn't attempt to pull the item towards the player until pickup delay finishes

**Comment by SuperMartijn642** [comment]
The magnets now won't pull in items you dropped yourself until the pickup delay runs out. Items not dropped by you will still be pulled in even if they have a pickup delay to prevent them from falling in lava for example.

Not exactly what you asked but I wanted to make sure dropped items still move with the player even when there is a pickup delay. At least you can now throw items to other players or dispose of them.

Thanks for the suggestion!

**Comment by KrAzYGEEK32** [comment]
That's exactly what I wanted😅, I just couldn't convey it properly. Thanks alot, and loving the mod❤️
