### ISSUE TITLE
[Bug] Mod Stopped Working completely

### ISSUE THREAD

**Issue by IllutianGunn** [SuperMartijn642/SimpleMagnets#12]
**Version Info*
- Minecraft, ...1.16.4 Forge 35.1.36
- Simple Magnets, simplemagnets-1.0.10-mc1.16.4.jar

**Description of the Bug**
...I upgraded from Forge 35.1.28 to 35.1.36 and the magnets, both versions stopped working completely.  I changed back and still not working at all.

**Steps to Reproduce**
...

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
What do you mean by 'stopped working completely'? Does Minecraft crash and if so can you send a crash report?
> I changed back and still not working at all.

Sounds like it's not this mod causing the issue then...

**Comment by UncleCrustyMC** [comment]
If the issue is the same as I am seeing, the magnets do not work. No errors, no crashes. You can hear the activation tone, but the magnet is not attracting anything- regular or advanced. let me know if I can provide more info.

**Comment by SuperMartijn642** [comment]
@UncleCrustyMC Thanks for the addition, I get what @IllutianGunn meant now.
Seems I somehow managed to remove an exclamation mark in the last update, now it is only picking up items *with* the 'PreventRemoteMovement' tag 🤦‍♂️

**Comment by SuperMartijn642** [comment]
I fixed it now in 1.0.10a-mc1.15, 1.0.10a-mc1.16.1, 1.0.10a-mc1.16.2, 1.0.10a-mc1.16.3, and 1.0.10a-mc1.16.4.

Thank you both for reporting the issue!
