### ISSUE TITLE
[Feature] Please add an AMZ (Anti-Magnet Zone) block

### ISSUE THREAD

**Issue by koalalord9999** [SuperMartijn642/SimpleMagnets#13]
**Is your feature request related to a problem? Please describe.**
No it's not a problem, just a suggestion

**Describe the solution you'd like**
It would be nice to have an items similar to the dislocator block in Draconic Evolution, that blocks its magnets from pulling items out of a small area around the block. I think that one is like 5x5 around  the block? Either way, would be nice to have this added to the mod, thanks :)

**Comment by SuperMartijn642** [comment]
I might add something block to prevent the magnet from picking up items at some point, however I am not quite sure yet.
In the meantime you could use [Demagnetize](https://www.curseforge.com/minecraft/mc-mods/demagnetize). I believe it adds exactly what you described.

**Comment by koalalord9999** [comment]
yea something like that would be very nice, only reason asking for it here, is im playing on a server pack for direwold20 1.16 -- and well you know, its kinda difficult to add mods to a server and hope that every player will actually cooperate ;)

**Comment by SuperMartijn642** [comment]
I added the 'Demagnetization Coil' and 'Advanced Demagnetization Coil' now which prevent magnets from teleporting items around them.
It is available in version 1.1.0.

Thanks for the suggestion!
