### ISSUE TITLE
[Feature] Can you add a item name when toggling the magnet?

### ISSUE THREAD

**Issue by koalalord9999** [SuperMartijn642/SimpleMagnets#15]
**Is your feature request related to a problem? Please describe.**
Not problem. Just suggestion

**Describe the solution you'd like**
When toggling the magnet (in my case, from a bauble slot) an item name "Magnet toggled: On/Off" would pop up in same spot as where when you're switching items on hot bar with mousewheel..? does that make sense? I don't know the technical name for this interaction, but that would be really nice for people who play without sounds :)

**Comment by SuperMartijn642** [comment]
That's a good suggestion, I will have to figure out how to do that.
When will I add it? No clue, I am also rather busy with other mods and school at the moment.

**Comment by SuperMartijn642** [comment]
I added it as an option in the config now in version 1.0.12.
It is disabled by default however, so you will need to turn it on to use it.

Thanks for the suggestion!

**Comment by koalalord9999** [comment]
It doesn't appear to work for me, I havnt test in single player, but it definitely doesn't work on my server :c (I enabled the config, and re-launched)
EDIT: Works in singleplayer
EDIT 2: Directly after trying in singleplayer, I jumped on my server to test it with both magnets. Can confirm, still doesn't work. Hmm

**Comment by SuperMartijn642** [comment]
Whoops seems I send the message and sounds from the server so it was taking the server's config values.

**Comment by SuperMartijn642** [comment]
I changed it now in version 1.0.13 so it uses the client's config settings.

Thanks for reporting it!

**Comment by koalalord9999** [comment]
^^
