### ISSUE TITLE
[Bug] MAJOR Dupe bug

### ISSUE THREAD

**Issue by Credit-Score** [SuperMartijn642/SimpleMagnets#16]
**Version Info**
- Minecraft, 1.16.4
- Simple Magnets, simplemagnets-1.0.13-mc1.16.5

**Description of the Bug**
You are able to dupe any stackable block in the game using this mod.

**Steps to Reproduce**
(All while wearing active magnet)                
1. Fill inventory with cobblestone, leave 2 slots open.
2. In 1 of those 2 slots, place a full stack of some block you want to dupe.
3. In the second slot, have like anywhere between 10 and 40 of the block you want to dupe.
4. Drop the 10-40 size stack, and replace it's spot with more cobblestone (So that now your inventory is full, and that 10-40 stack is just following you around
5. You can now infinitely place the block without ever running out.

**Screenshots**
Setup
![image](https://user-images.githubusercontent.com/63371073/107669045-f6e32280-6c56-11eb-97d0-d847125282cd.png)
Now with redstone item always following me due to magnet
![image](https://user-images.githubusercontent.com/63371073/107669104-0498a800-6c57-11eb-9e6a-b7fe535005f3.png)"
Annnnd ton of redstone placed
![image](https://user-images.githubusercontent.com/63371073/107669321-39a4fa80-6c57-11eb-82f9-83ce308d19b5.png)
Look at that! Still got my redstone
![image](https://user-images.githubusercontent.com/63371073/107669375-49244380-6c57-11eb-898a-aa4a22054ebd.png)

**Comment by SuperMartijn642** [comment]
Jup that's a pretty bad one, I will look into it.

**Comment by SuperMartijn642** [comment]
It doesn't seem to happen when I test it. Actually the magnets don't even do anything with the items, they only teleport the item entity to the player.

Can you test if it still happens when just using Simple Magnets?

Whoops didn't mean to close the issue.

**Comment by Credit-Score** [comment]
No I cannot. Another thing I noticed is with only simple magnets, the item moves extremely smoothly following you, but with all the other mods it's quite jerky, leaving a bunch of after-images from teleporting forward and back so much.

**Comment by SuperMartijn642** [comment]
It's rather smooth because I move the items both on the server-side and on the client-side.

I will close the issue then as it doesn't have to do with Simple Magnets.

**Comment by Credit-Score** [comment]
You are correct, I tested with other magnets (including Botania) and it still happens. Obviously some other mod is messing it up
       
EDIT: In fact, no magnet needed. You can have it on the ground under you and it still happens. Oooof. Sorry too have wasted your time by not doing more testing, just never assume it would happen no matter what!
