### ISSUE TITLE
[Feature] Custom sounds for on/off

### ISSUE THREAD

**Issue by abint** [SuperMartijn642/SimpleMagnets#17]
**Is your feature request related to a problem? Please describe.**
As someone who can't often play with sound, I rely on the in-game subtitles for auditory info. Since the mod uses the noteblock sound for both on and off and subtitles doesn't differentiate between different notes, I find myself always second guessing if my magnet is on or off.

**Describe the solution you'd like**
To make the mod more accessible for hard of hearing and game muted players, I suggest that the mod introduce its own custom sounds for on and off, and set according descriptions for the subtitles. The sounds could very well be a copy of the noteblock sounds, just separate in game files to let you set a custom name.

**Comment by SuperMartijn642** [comment]
There's a config option to show a message above the hotbar when the magnet is turned on or off.
I think that would solve your problem.

**Comment by abint** [comment]
Damn 1.16 forge and its lack to change like 90% of configs in game. I should've checked the config folder and text files. This does solve the issue. Don't know why its not on by default

**Comment by SuperMartijn642** [comment]
I was indeed debating whether to turn it on by default when I added it.
I will probably change it to be on by default in the next update.
