### ISSUE TITLE
[Feature] Magnetic Chest

### ISSUE THREAD

**Issue by winsrp** [SuperMartijn642/SimpleMagnets#20]
**Describe the solution you'd like**
Well a magnetic chest, that attracts items to it... also advanced magnetic chest would be cool.

And while we are at it, why not a magnetic mine cart, never seen that before, but I can think of several uses right of the top of my head. It could use a stronger/improved magnet version, to just suck items right in, instead of pull them slowly.

thanks!

**Comment by SuperMartijn642** [comment]
Actually, I have another mod which adds item collectors. It is called [Item Collectors](https://www.curseforge.com/minecraft/mc-mods/item-collectors). So I won't be a adding something like that to this mod.

As for the magnetic minecart, that does sound neat. I'm not quite sure yet whether I'll add it. Anyways, it will be a while before I am working on mods again, so I will decide then.

**Comment by winsrp** [comment]
sounds cool, tx
