### ISSUE TITLE
[Bug] Uncommented comments in mods.toml

### ISSUE THREAD

**Issue by srs-bsns** [SuperMartijn642/SimpleMagnets#21]
In commit: c7069d402719e531f8a7c2e7a17fcd6f343d46bc you erroneously uncommented comments in the mods.toml which prevents loading:
https://github.com/SuperMartijn642/SimpleMagnets/commit/c7069d402719e531f8a7c2e7a17fcd6f343d46bc#diff-3bc2a2f6cb6e625914eaf245e536e39108fbc2a24acd076bd6bbc2a60f56c214R54
https://github.com/SuperMartijn642/SimpleMagnets/commit/c7069d402719e531f8a7c2e7a17fcd6f343d46bc#diff-3bc2a2f6cb6e625914eaf245e536e39108fbc2a24acd076bd6bbc2a60f56c214R61

**Comment by SuperMartijn642** [comment]
Jup 🤦‍♂️
At least I should be able to properly test it now that 37.0.2 is available.

I will probably fix later today

**Comment by SuperMartijn642** [comment]
I fixed it now in 1.1.2a for Minecraft 1.17.

Thank you for reporting the issue!
