### ISSUE TITLE
[Crash] Crash while dropping item 

### ISSUE THREAD

**Issue by KrolMC** [SuperMartijn642/SimpleMagnets#22]
Hello,
When I updated Simple Magnets mod to the latest versions game crashes when I dropped my first item on the world ;c

**Version Info**
- Minecraft: 1.17.1
- Simple Magnets: 1.1.2a

**Crash report (~/logs/latest.log)**
[crash-2021-07-24_14.59.04-server.txt](https://github.com/SuperMartijn642/SimpleMagnets/files/6872444/crash-2021-07-24_14.59.04-server.txt)

**Comment by SuperMartijn642** [comment]
I fixed a number of issues in Simple Magnets 1.1.2b for 1.17, however I couldn't find any issues with dropping and picking up items.
Is there anything special you did? Or is there another mod that also does stuff with item entities?

**Comment by KrolMC** [comment]
I simply created a world, and I dropped the Gold Bush from Metal Bushes mod and my game crashes. I'll update forge and my mods, if the problem fixes itself I will close the issue.

**Comment by KrolMC** [comment]
game still crashes when i drop item ;/

**Comment by Gbergz** [comment]
Can confirm this is the case, picking up a seed from a Fern crashes the game. (Prob any item)
https://gist.github.com/Gbergz/48216d690ba6f21bf0069e0473f67093

Mod Jar: simplemagnets-1.1.2b-mc1.17.jar

**Comment by SuperMartijn642** [comment]
I finally found the issue now and it is fixed in 1.1.2c for 1.17.

Thank you both for reporting the issue and helping me out!
