### ISSUE TITLE
Error during event phase

### ISSUE THREAD

**Issue by Baggytrousers27** [SuperMartijn642/SimpleMagnets#24]
supermartijn642configlib-1.0.9-mc1.17
supermartijn642corelib-1.0.12-mc1.17
Simplemagnets 1.1.2d mc1.17
Forge 17.17.1-37.0.31(33)

Simple Magnets (Simple Magnets) encountered an error during the common_setup event phase.

Simple Magnets (Simple Magnets) encountered an error during the error event phase.

[Crashlog](https://pastebin.com/k6DLdjvj)

**Comment by SuperMartijn642** [comment]
I fixed it now in Simple Magnets version 1.1.2e.

Thank you for reporting the issue!
