### ISSUE TITLE
[Bug] Errors in the currently selected datapacks

### ISSUE THREAD

**Issue by Baggytrousers27** [SuperMartijn642/SimpleMagnets#25]
**Version Info**
- Minecraft, 1.17.1 37.0.41/42 (Crashes before opening in 37.0.31/33/34/36/39)
- Simple Magnets, 1.1.2e-mc1.17
- supermartijn642configlib-1.0.9-mc1.17
- supermartijn642corelib-1.0.12-mc1.17

**Description of the Bug**
Upon trying to load up a world or start a new one.
Errors in the currently selected datapacks prevent the world from loading.
You can either try to load it with only the vanilla datapack ("safe mode"), or go back to the title screen and fic is manually.

**Steps to Reproduce**
As above

**Screenshots**
![Screenshot 2021-08-23 015054](https://user-images.githubusercontent.com/15883796/130361592-fe412bc2-745a-4b69-becf-335883f874e6.png)

[Log](https://pastebin.com/cCmp8Kxh)

Sorry to be the bearer of bad news but here we are again.

**Comment by SuperMartijn642** [comment]
Yup, I definitely derped. I fixed it now in Simple Magnets 1.1.2f for 1.17.

Thanks again!
