### ISSUE TITLE
[Bug][Visual only] Items in demagnetization zones are visually pulled to you if they are updated / freshly dropped.

### ISSUE THREAD

**Issue by sh4ni** [SuperMartijn642/SimpleMagnets#27]
**Version Info**
- simplemagnets-1.1.2-mc1.16.5
- I'm playing on a Server

**Description of the Bug**
If you set up a Demagnetization coil and items in there are dropped by others or are updated, they are visually pulled to the player which looks extremely annoying.
They are not pulled to your inventory, because the zone blocks it, but it still looks like it.

**Steps to Reproduce**
- Set up a Demagnetization Coil
- Put a Dropper with Items and a Button in the Zone
- Push the Button
- The Item will look like it flies to your inventory

**Comment by SuperMartijn642** [comment]
I fixed it now in version 1.1.3.

Thank you for reporting the issue!
