### ISSUE TITLE
[Feature] Compat with ItemPhysic mod

### ISSUE THREAD

**Issue by p1ut0nium-git** [SuperMartijn642/SimpleMagnets#28]
Is there any way to make this mod work with ItemPhysic? https://www.curseforge.com/minecraft/mc-mods/itemphysic

Current behavior:

- enable magnet in hot bar
- Mine cobblestone
- Cobblestone drops & is pulled to player’s feet by magnet, but not picked up
- Must right click or sneak to pick up (this is ItemPhysic in action)

Desired Behavior:

Dropped items pulled by magnet should go into player inventory without needing to be picked up via ItemPhysic, but when magnet is disabled typical ItemPhysic custom pickup should work as usual.

**Comment by SuperMartijn642** [comment]
I added a special case for ItemPhysic to just directly add items to the player's inventory. It's available in Simple Magnets 1.1.3.

Thank you for the suggestion!
