### ISSUE TITLE
1.16.2 Crash when having the magnet in off-hand and try to enter the magnet GUI.

### ISSUE THREAD

**Issue by RodrigoNMiers** [SuperMartijn642/SimpleMagnets#3]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 16/08/20 00:01
Description: Rendering screen

java.lang.ArrayIndexOutOfBoundsException: null

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:494)

-- Screen render details --
Details:
	Screen name: com.supermartijn642.simplemagnets.gui.MagnetContainerScreen
	Mouse location: Scaled: (341, 192). Absolute: (683.000000, 384.000000)
	Screen size: Scaled: (683, 384). Absolute: (1366, 768). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:494)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:954)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:585)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Rodrigonmiers'/142, l='ClientLevel', x=-1842.70, y=63.00, z=510.35]]
	Chunk stats: Client Chunk Cache: 841, 575
	Level dimension: minecraft:overworld
	Level spawn location: World: (-192,64,16), Chunk: (at 0,4,0 in -12,1; contains blocks -192,0,16 to -177,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 11223774 game time, 12921076 day time
	Server brand: forge
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 360579176 bytes (343 MB) / 984989696 bytes (939 MB) up to 4231266304 bytes (4035 MB)
	CPUs: 4
	JVM Flags: 6 total; -Xmn128M -Xmx4047M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UseConcMarkSweepGC -XX:MaxPermSize=1000M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.2-33.0.2.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.2.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.2-33.0.2.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.2.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.2-33.0.2.jar fml TRANSFORMATIONSERVICE 
	FML: 33.0
	Forge: net.minecraftforge:33.0.2
	FML Language Providers: 
		javafml@33.0
		minecraft@1
	Mod List: 
		forge-1.16.2-33.0.2-client.jar Minecraft {minecraft@1.16.2 DONE}
		doubledoors_1.16.2-2.1.jar Double Doors {doubledoors@2.1 DONE}
		forge-curioofundying-1.16.2-5.0.0.0.jar Curio of Undying {curioofundying@1.16.2-5.0.0.0 DONE}
		bspawncontrol_1.16.2-1.1.jar Better Spawner Control {bspawncontrol@1.1 DONE}
		Compressium-1.0.27.jar Compressium {compressium@1.16.2-1.0.4 DONE}
		expandedstorage-3.0.0+1.16.2.jar Expanded Storage {expandedstorage@3.0.0 DONE}
		TrashSlot_1.16.2-12.1.0.jar TrashSlot {trashslot@12.1.0 DONE}
		simplemagnets-1.0.4a-mc1.16.jar Simple Magnets {simplemagnets@1.0.4a DONE}
		curiouselytra-forge-1.16.2-4.0.0.0.jar Curious Elytra {curiouselytra@1.16.2-4.0.0.0 DONE}
		shulkerbox-1.16.2-1.0.1.jar Advanced Shulkerboxes {shulkerbox@1.16.2-1.0.1 DONE}
		jei-1.16.2-7.1.0.11.jar Just Enough Items {jei@7.1.0.11 DONE}
		easyelytrato_1.16.2-1.4.jar Easy Elytra Takeoff {easyelytrato@1.4 DONE}
		FallingTree-Forge-1.16.2-2.2.1.jar Falling Tree {falling_tree@2.2.1 DONE}
		simplybackpacks-1.16.2-1.4.10.jar Simply Backpacks {simplybackpacks@1.16.2-1.4.10 DONE}
		caelus-forge-1.16.2-2.0.0.0.jar Caelus API {caelus@1.16.2-2.0.0.0 DONE}
		forge-1.16.2-33.0.2-universal.jar Forge {forge@33.0.2 DONE}
		jeiintegration_1.16.2-5.0.0.6.jar JEI Integration {jeiintegration@5.0.0.6 DONE}
		infinitetrading_1.16.2-1.1.jar Infinite Trading {infinitetrading@1.1 DONE}
		CraftingCraft_1.16.2-9.1.0.jar CraftingCraft {craftingcraft@9.1.0 DONE}
		reap-1.16.2-1.0.1.jar Reap Mod {reap@1.16.2-1.0.1 DONE}
		invtweaks-1.16.2-1.0.0.jar Inventory Tweaks Renewed {invtweaks@1.16.2-1.0.0 DONE}
		curios-forge-1.16.2-4.0.0.0.jar Curios API {curios@1.16.2-4.0.0.0 DONE}
		gravestone-1.16.1-1.0.1.jar Gravestone Mod {gravestone@1.16.1-1.0.1 DONE}
		collective-1.16.2-1.37.jar Collective {collective@1.37 DONE}
		CraftingTweaks_1.16.2-12.1.0.jar Crafting Tweaks {craftingtweaks@12.1.0 DONE}
	Launched Version: 1.16.2-forge-33.0.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce 210/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla (incompatible), mod_resources (incompatible)
	Current Language: Español (España)
	CPU: 4x Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz

**Comment by SuperMartijn642** [comment]
I fixed it now in version 1.0.5.

Thanks for the report!
