### ISSUE TITLE
[Crash] Scaling GUI causes crashes upon loading the world until entire mods removal

### ISSUE THREAD

**Issue by grammyy** [SuperMartijn642/SimpleMagnets#34]
**Version Info**
- Minecraft, 1.18.2
- Simple Magnets, simplemagnets-1.1.7-forge-mc1.18

**Steps to Reproduce**
Change the GUI scale while in-game with a large amount of RAM allocated (8000MB)
**Crash report (~/logs/latest.log)**
[crash-2022-06-01_23.06.07-fml.txt](https://github.com/SuperMartijn642/SimpleMagnets/files/8820405/crash-2022-06-01_23.06.07-fml.txt)

**Comment by SuperMartijn642** [comment]
The log file shows the game crashed on startup, before you can load a world or change the gui scale 🤔

The crash seems to come from an error when trying to load chunk loaders' config file.

**Comment by grammyy** [comment]
It does seem strange, but it's the only thing I could think of as I was standing in a field with normal oak trees. I simply changed the GUI scale 3 times to cycle around back to 1. The game crashed saying exception on simplemagnets and continued until I removed it from the game files.

**Comment by SuperMartijn642** [comment]
Looking at the log on my computer now, it looks like the config file is just messed up. `Table with path [Client] has been declared twice.` is the error it gives.

Could you see if deleting the config file fixes the issue?

**Comment by grammyy** [comment]
That worked, thank you. Not sure how it got messed up.
