### ISSUE TITLE
[Bug] Magnet not disabled by Botania’s solegnolia flower

### ISSUE THREAD

**Issue by Nevrai** [SuperMartijn642/SimpleMagnets#36]
The mod [Botania](https://www.curseforge.com/minecraft/mc-mods/botania) has a flower called the [solegnolia](https://ftb.fandom.com/wiki/Solegnolia), which disables magnetization rings in a small radius, but it doesn’t disable Simple Magnets’ magnet.

I realized whilst writing this that Simple Magnets does have a demagnetization coil, but it would be nice if Botania’s solegnolia also worked.

### Versions
* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7/files/) (version 0.4.25—latest)
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **Simple Magnets:** 1.1.8 (latest for 1.18.2)
* **Botania:** 434 (latest)

**Comment by SuperMartijn642** [comment]
The magnets will ignore any item entities which have the `PreventRemoteMovement` nbt tag. This a community standard which pretty much all magnet mods respect. This includes larger mods such as Thermal Innovation.
This is also how other mods' anti-magnet blocks work, for example [Demagnetize](https://www.curseforge.com/minecraft/mc-mods/demagnetize).

I will not be adding specific compatibility for Botania. Doing so means I would have to add specific compatibility for every mod which adds some sort of anti-magnet block.
Instead, I suggest Botania also uses the `PreventRemoteMovement` nbt tag. This would also make botania compatible with other magnet mods (such as Thermal Innovation, Tiered Magnets, Ring of Attraction, Ender Magnet, etc.).
