### ISSUE TITLE
[Bug] Spectator Mode

### ISSUE THREAD

**Issue by DinnerBeef** [SuperMartijn642/SimpleMagnets#37]
**Version Info**
- Minecraft, 1.18.2
- Simple Magnets, 1.1.8

**Description of the Bug**
If you are in spectator mode and magnet is still on you still suck up items, However you did not pick them up

**Steps to Reproduce**
Turn on magnet and go to spectator mode.

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.1.9.

Thank you for reporting the issue!
