### ISSUE TITLE
[Feature] Add effect to disable Item Magnet

### ISSUE THREAD

**Issue by UdoMorgenstern** [SuperMartijn642/SimpleMagnets#39]
**Is your feature request related to a problem? Please describe.**
Having certain minigames an item magnet might be used to cheat, while a demagnitizer can be used in small areas its not a solution for large areas 

**Describe the solution you'd like**
Add an effect to disable item magnets for a given time
`/efffect give [target] simplemagnets:disabled 500`

**Comment by SuperMartijn642** [comment]
Your use case seems rather specific. I don't want to add and maintain such an effect which will likely never be used by others.

Additionally, you can change the maximum radius of the demagnetization coils in Simple Magnets' config file. It can be increased up to a radius of 10 blocks, which I feel should be sufficient.

**Comment by UdoMorgenstern** [comment]
well in my case i made a game like "iskalls diamond jump" - so item will fall over 200 blocks down, while the player jumps after them trying to catch these. So 10 block if far to low.

but well again, just a suggestion. As mods like "xaeros minimaps" have such features it was worth to ask.

**Comment by UdoMorgenstern** [comment]
Never mind after checking your source code, and the checking the items data ingame, i figured out that the booleans you set to the items (PreventRemoteMovement and AllowMachineRemoteMovement) are not updated after the items went thru a demag. coil. so i can use this feature to prevent cheating in these kind of minigames
