### ISSUE TITLE
[1.16.1] Magnets don't seem to pick up XP

### ISSUE THREAD

**Issue by WhitePhant0m** [SuperMartijn642/SimpleMagnets#4]
simplemagnets-1.0.5-mc1.16.1
forge: 32.0.108

maybe not working because of [clumps ](https://www.curseforge.com/minecraft/mc-mods/clumps)mod? If that is the cause, could you add compat for it?

[![Image from Gyazo](https://i.gyazo.com/91f0ef785f99c6e3fdbd09e95ea6962c.gif)](https://gyazo.com/91f0ef785f99c6e3fdbd09e95ea6962c)

**Comment by SuperMartijn642** [comment]
I made it work with Clumps now in version 1.0.6.

Thanks for the suggestion!
