### ISSUE TITLE
[Crash] Server crash in the latest version (1.1.9 in 1.16.5)

### ISSUE THREAD

**Issue by Koynax** [SuperMartijn642/SimpleMagnets#40]
- Minecraft 1.16.5
- Simple Magnets 1.1.9

Hello, 
When putting the latest update on my server, the mod crashes it. I don't know how to fix this, can you please help me ? On the Automanism Modpack. The mod crashes only on the server, in singleplayer everything is fine.

[latest.log]
https://github.com/SuperMartijn642/SimpleMagnets/files/10355362/latest.log

[crash-2023-01-05_20.52.28-fml.txt]
https://github.com/SuperMartijn642/SimpleMagnets/files/10355368/crash-2023-01-05_20.52.28-fml.txt

**Comment by SuperMartijn642** [comment]
Fixed it now in version 1.1.0b of my core library for Minecraft 1.16.

Thank you for reporting the issue!

**Comment by Koynax** [comment]
> Fixed it now in version 1.1.0b of my core library for Minecraft 1.16.
> 
> Thank you for reporting the issue!

Wow you are fast ! Thanks for the fix !
I will update it again in the next update of my modpack
