### ISSUE TITLE
[Crash] 1.19.4 Crash to Desktop

### ISSUE THREAD

**Issue by Crystallyne** [SuperMartijn642/SimpleMagnets#43]
**Version Info**
- Minecraft, 1.19.4
- Simple Magnets, 1.1.9 (simplemagnets-1.1.9-forge-mc1.19.3.jar)
- Forge, 45.0.9

**Steps to Reproduce**
Using CurseForge, create a new profile for 1.19.4. Install Simple Magnets, and load the game.
Create a new world. (I used Creative for testing purposes.)
Within a couple minutes, the game crashes to desktop.

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/SimpleMagnets/files/11023857/latest.log)

**More Details**
Initially I added this along with several other mods. At the time, I was at Y level -59, doing some strip mining. On loading, my game completely froze (Not Responding) and wouldn't allow me to play. I disabled my newest mods one by one to identify this one as the culprit.

For this crash report, I disabled all of the mods (in CurseForge) except this one, along with the configlib and corelib that are required. I created a new world in creative mode, and crashed fairly quickly. (Within 5 minutes or less, wasn't timing it.)

**Comment by SuperMartijn642** [comment]
Should work with the dedicated file for 1.19.4 for now.
Thank you for reporting the issue!
