### ISSUE TITLE
[Feature] Add togglable area of effect to Demagnetization Coils

### ISSUE THREAD

**Issue by penturt** [SuperMartijn642/SimpleMagnets#49]
Unless I'm doing something wrong the only way to currently view the area of effect of the Demagnetization Coils is to look at the coils themselves and the area highlights around it.

Is it possible to make that effect something toggleable within the coil's gui, so a player to toggle it on an step away to clearly see the full area covered? Its just that the way it currently is depending on the size its kind of hard to see the full area its effecting without changing the FOV.

**Comment by penturt** [comment]
neverminded just saw the latest version lol

**Comment by SuperMartijn642** [comment]
Indeed I just added that a couple days ago lol, perfect timing.
