### ISSUE TITLE
[Bug] CTD When dropping items

### ISSUE THREAD

**Issue by Jebushacks** [SuperMartijn642/SimpleMagnets#50]
**Version Info**
- Minecraft, 1.20.4
- Simple Magnets,1.1.10

**Description of the Bug**
Everything was running fine, then I dropped an item from my inventory and crashed to desktop.

**Steps to Reproduce**
Either using the hotkey or manually dropping the item will do the trick

**Screenshots**
...
[2023-12-09-7.log.gz](https://github.com/SuperMartijn642/SimpleMagnets/files/13623962/2023-12-09-7.log.gz)

**Comment by SuperMartijn642** [comment]
Fixed now in the dedicated version for 1.20.4.
Thank you for reporting the issue!
