### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by Crazyinak** [SuperMartijn642/SimpleMagnets#54]
**Version Info**
- Minecraft, ...
- Simple Magnets, ...

**Description of the Bug**
...i dont have any way to put the magnet in to the curos slot i am useing 1.20.1 and curseForge

**Steps to Reproduce**
...

**Screenshots**
...
![Screenshot 2024-02-26 224449](https://github.com/SuperMartijn642/SimpleMagnets/assets/96904236/ea1cc4e4-8bc8-486c-96ac-b91ff04aab31)

**Comment by SuperMartijn642** [comment]
Please fill in the template, it's there for a reason. I have no clue what Minecraft version or modloader you are even using.

**Comment by Crazyinak** [comment]
sorry about that i fixed it

**Comment by SuperMartijn642** [comment]
What version of Simple Magnets are you using?

**Comment by Crazyinak** [comment]
1.1.10
