### ISSUE TITLE
[Bug] Simple Magnets 1.1.11 for Fabric 1.20 disabling magnet with hotkey does not disable it

### ISSUE THREAD

**Issue by calloatti** [SuperMartijn642/SimpleMagnets#56]
**Version Info**
- Minecraft, 1.20.1
- Simple Magnets, Simple Magnets 1.1.11 for Fabric 1.20

**Description of the Bug**

Pressing H to disable the magnet, Message "Magnet: Off" is shown but the magnet still works.

**Steps to Reproduce**

Update from simplemagnets-1.1.10-fabric-mc1.20.jar to simplemagnets-1.1.11-fabric-mc1.20.jar

Works fine in 1.1.10 

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
That's odd, nothing has changed between 1.1.10 and 1.1.11. I only added two language files.

**Comment by calloatti** [comment]
Yes, you are right. 1.1.10 has the same problem, turning the magnet off does nothing.

**Comment by calloatti** [comment]
Anyway, will have to do more testing, this started happening recently and may be due to some other mod maybe?

**Comment by SuperMartijn642** [comment]
I cannot reproduce the issue, the keybind seems to work fine. After toggling the magnet to off using the keybind, no items get picked up.
