### ISSUE TITLE
[Bug] trikets solt don't use and translation key bug

### ISSUE THREAD

**Issue by bakrun** [SuperMartijn642/SimpleMagnets#59]
**Version Info**
- Minecraft, ... 1.21 fabric
- Simple Magnets, ... 1.1.11

**Description of the Bug**
...
trinket slot don't using 

trinkets slot path replace  data/trikets/tags/item/hand/ring.json 
items -> item 

translation key need change 
example  "gui.advancedmagnet.title": "고급 자석", -> 
this.translation("simplemagnets.gui.magnet.title", "고급 자석");

**Steps to Reproduce**
...

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
The Trinkets slots should be fixed now in Simple Magnets version 1.1.11a/b.

> translation key need change
example "gui.advancedmagnet.title": "고급 자석", ->
this.translation("simplemagnets.gui.magnet.title", "고급 자석");

I don't do translations for other languages, they are all submitted by people in the community. If you want changes to the translations, you can submit a pull request.
That being said, there is currently already a pull request for it (#57), so will likely be updated not too long from now.

Thank you for reporting the issue!
