### ISSUE TITLE
Advanced Magnet still not letting fishing pole with mending get repaired

### ISSUE THREAD

**Issue by TheOrionsun** [SuperMartijn642/SimpleMagnets#6]
MC 1.15.2, Forge 31.2.36 Simplemagnets-1.0.6-mc1.15

I just updated mod seeing you fixed XP/mending issue and I still have to disable the advanced magnet for my fishing pole to receive xp to mend.

Update:
I noticed it only blocks if magnet is in the Charm slot...just tried it again and the magnet was in an equipment slot and it let the fishing pole gain durability. 

Looks like I just needed to disable and reenable magnet to have it work as intended with magnet in charm slot.

Sorry, looks like all is well....going to cancel if you see this....

Thank you

**Comment by TheOrionsun** [comment]
Closing issue as I just needed to disable and enable magnet to get issue to correct....

**Comment by SuperMartijn642** [comment]
Still weird that it didn't work immediately, but I'm glad it fixed itself 😄
