### ISSUE TITLE
[Feature] Support for Trinkets API on Fabric

### ISSUE THREAD

**Issue by AndrewGraber** [SuperMartijn642/SimpleMagnets#61]
**Is your feature request related to a problem? Please describe.**
The mod has support for baubles/curios slots, so that magnets don't take up an inventory space, but Fabric now has the Trinkets API which doesn't have support

**Describe the solution you'd like**
Add support for the Trinkets API for Fabric

**Comment by SuperMartijn642** [comment]
Simple Magnets already has support for Trinkets API. If it does not work with Trinkets slots then that's likely a bug.
