### ISSUE TITLE
[Bug] Demagnetization coil configuration

### ISSUE THREAD

**Issue by KyBeeS** [SuperMartijn642/SimpleMagnets#65]
**Version Info**
- Minecraft, 1.21.1 neo
- Simple Magnets, Latest
-Pack, All the Mods 10 v1.1

**Description of the Bug**
on reload configuration settings 

**Steps to Reproduce**
![Screenshot_2024-10-18-12-23-31-48_572064f74bd5f9fa804b05334aa4f912.jpg](https://github.com/user-attachments/assets/c855e3c9-a1f8-4b34-a426-2e21e2c215a8)

**Screenshots**

**Comment by SuperMartijn642** [comment]
This is fixed now in version 1.1.12 of Simple Magnets.
Thank you for reporting the issue!
