### ISSUE TITLE
[Crash] Unexpected server crash when throwing an item while the magnet is on

### ISSUE THREAD

**Issue by DaytonaBlep** [SuperMartijn642/SimpleMagnets#66]
**Version Info**
- Forge, 47.3.11
- Minecraft, 1.20.1
- Simple Magnets, 1.1.12

**Steps to Reproduce**
I was sailing on a boat while the **Advanced Magnet** was on, accidentally picked up some kelp, pressed Q on the go to throw it away and the server instantly crashed.
More details, I got a same crash when I activated the magnet in my hands and there were no items for attract around, the same error.

**Crash report (~/logs/latest.log)**
[crash-2024-10-19_10.32.56-server.txt](https://github.com/user-attachments/files/17444274/crash-2024-10-19_10.32.56-server.txt)
[latest.log](https://github.com/user-attachments/files/17444275/latest.log)

**Comment by DaytonaBlep** [comment]
Some addition, opening the world now instantly causes the same crash over and over again

**Comment by mac2040** [comment]
I'm having the same problem

**Comment by icha-senpai** [comment]
same problem, i'm going to use 1.1.11 for the time being

**Comment by tacogerbil** [comment]
Same here.. but I haven't even made a magnet yet.  Threw some coal and got booted.
After being booted I coldn't get back into the server till I replaced the mod with the older version.
Forge, 47.3.10
Minecraft, 1.20.1
Simple Magnets, 1.1.12

**Comment by Paulie820** [comment]
Also experienced this, "exception ticking world" crash when I accidentally dropped a cooked chicken with Q. Downgrading to 1.1.11 fixes the issue.
[crash-2024-10-19_14.57.33-server.txt](https://github.com/user-attachments/files/17446994/crash-2024-10-19_14.57.33-server.txt)

**Comment by thomwoosley** [comment]
I had this error too, but also an even worse one where when starting up the world would freeze as terrain was loading and simply hang.

**Comment by vizthex123** [comment]
Same issue here, but mine didn't start crashing until I updated Alex's Caves to the new 2.0 update.
[latest.log](https://github.com/user-attachments/files/17447487/latest.log)

**Comment by muppetenergy** [comment]
i'm having the same issue as well, server crashed after updating and trying to turn magnet on 
can't post crash report because it's stuck on shutting down process

**Comment by SuperMartijn642** [comment]
This should be fixed now in the dedicated file for 1.20.1.
Thank you for reporting the issue!
