### ISSUE TITLE
[Bug] Advanced Demagnetization Coil doesn't pick up items or XP

### ISSUE THREAD

**Issue by FoxySophie** [SuperMartijn642/SimpleMagnets#67]
**Version Info**
- Minecraft, 1.20.1
- Simple Magnets, 1.1.12

**Description of the Bug**
From what I understand the Advanced Demagnetization Coil is supposed to pick up XP and Items in a 3 block radius around it? That doesn't seem to work.

**Steps to Reproduce**
Place down coil. Drop items right next to it. Nothing happens.

**Screenshots**
![image](https://github.com/user-attachments/assets/86c78365-eb18-4d6e-bec8-fb4893331021)

**Comment by SuperMartijn642** [comment]
The demagnetization coil prevents items from being picked up by magnets.
![image](https://github.com/user-attachments/assets/60abe7bc-e202-4998-a0bb-04d8d2439c23)

**Comment by SuperMartijn642** [comment]
Perhaps you are confusing it with the advanced item collector? https://www.curseforge.com/minecraft/mc-mods/item-collectors

**Comment by FoxySophie** [comment]
Not quite, the reason I was asking is because of this setting in the config for SimpleMagnets:

```
# In what range should the Advanced Demagnetization Coil pickup items and xp by default?
# Allowed range: 1 ~ 10 - Default: 3
advancedCoilRange = 3
```

I guess it's just a mistake in the description for that setting?

**Comment by SuperMartijn642** [comment]
Ah I see, yeah I probably just copied it from my Item Collectors mod and forgot to change it
