### ISSUE TITLE
[Bug] Integrated Dynamics compatibility

### ISSUE THREAD

**Issue by uhloin** [SuperMartijn642/SimpleMagnets#68]
**Version Info**
- Minecraft, 1.21.1
- Simple Magnets, simplemagnets-1.1.12-neoforge-mc1.21.jar 

**Description of the Bug**
See
https://github.com/CyclopsMC/IntegratedTerminals/issues/137
https://github.com/CyclopsMC/IntegratedTerminals/issues/130

**Comment by SuperMartijn642** [comment]
It should be fixed now in Simple Magnets version 1.1.12a for 1.20.5 - 1.21.3.
Thank you for reporting the issue!

**Comment by uhloin** [comment]
Thank you very much
