### ISSUE TITLE
[Crash] ... Changing Options for Advanced Magent on Multiplayer Server

### ISSUE THREAD

**Issue by MararoYolowaty** [SuperMartijn642/SimpleMagnets#69]
**1.1.12a**
- Minecraft 1.21.3 Fabric
- Simple Magnets

**Steps to Reproduce**
Shift-right click an advanced magnet on a multiplayer to change its config/options and it will crash the game.

**Crash report (~/logs/latest.log)**
`---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-11-10 00:36:24
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.util.ImmutableCollections.listFromArray(ImmutableCollections.java:192)
	at java.base/java.util.List.of(List.java:1172)
	at knot//com.supermartijn642.simplemagnets.AdvancedMagnet$Settings.defaultSettings(AdvancedMagnet.java:133)
	at knot//com.supermartijn642.simplemagnets.gui.MagnetContainerScreen.renderForeground(MagnetContainerScreen.java:111)
	at knot//com.supermartijn642.simplemagnets.gui.MagnetContainerScreen.renderForeground(MagnetContainerScreen.java:21)
	at knot//com.supermartijn642.core.gui.widget.ObjectBaseContainerWidget.renderForeground(ObjectBaseContainerWidget.java:183)
	at knot//com.supermartijn642.core.gui.WidgetContainerScreen.method_25394(WidgetContainerScreen.java:128)
	at knot//net.minecraft.class_437.method_47413(class_437.java:116)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$83(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$zpf000$fabric-screen-api-v1$onRenderScreen(class_757.java:1412)
	at knot//net.minecraft.class_757.method_3192(class_757.java:549)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1352)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.util.ImmutableCollections.listFromArray(ImmutableCollections.java:192)
	at java.base/java.util.List.of(List.java:1172)
	at knot//com.supermartijn642.simplemagnets.AdvancedMagnet$Settings.defaultSettings(AdvancedMagnet.java:133)
	at knot//com.supermartijn642.simplemagnets.gui.MagnetContainerScreen.renderForeground(MagnetContainerScreen.java:111)
	at knot//com.supermartijn642.simplemagnets.gui.MagnetContainerScreen.renderForeground(MagnetContainerScreen.java:21)
	at knot//com.supermartijn642.core.gui.widget.ObjectBaseContainerWidget.renderForeground(ObjectBaseContainerWidget.java:183)
	at knot//com.supermartijn642.core.gui.WidgetContainerScreen.method_25394(WidgetContainerScreen.java:128)
	at knot//net.minecraft.class_437.method_47413(class_437.java:116)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$83(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$zpf000$fabric-screen-api-v1$onRenderScreen(class_757.java:1412)

-- Screen render details --
Details:
	Screen name: com.supermartijn642.core.gui.WidgetContainerScreen
	Mouse location: Scaled: (256, 144). Absolute: (1280.000000, 720.000000)
	Screen size: Scaled: (512, 288). Absolute: (2560, 1440). Scale factor of 5.000000
Stacktrace:
	at knot//net.minecraft.class_757.method_3192(class_757.java:549)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1352)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 53.292s
	Wall uptime: 43.338s
	High-res time: 41.069s
	Client ticks: 732 ticks / 36.600s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2443)
	at knot//net.minecraft.class_310.method_54580(class_310.java:1002)
	at knot//net.minecraft.class_310.method_1514(class_310.java:954)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['MararoYolowaty'/50116, l='ClientLevel', x=-969.33, y=93.00, z=-60.02]]
	Chunk stats: 3025, 1021
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,76,0), Section: (at 0,12,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 16742691 game time, 17727140 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
	Tracked entity count: 279

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/VanillaTweaks_r125377_MC1.21.x.zip, fabric, betterf3, cloth-config, durabilitytooltip, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, itemscroller, journeymap, malilib, minihud, modmenu, placeholder-api, polymer-core, polymer-resource-pack, silk-all, simplemagnets, sodium, sodium-extra, supermartijn642corelib, tweakeroo, universal-graves, veinminer

-- System Details --
Details:
	Minecraft Version: 1.21.3
	Minecraft Version ID: 1.21.3
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 495499320 bytes (472 MiB) / 973078528 bytes (928 MiB) up to 25769803776 bytes (24576 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660 SUPER
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 6144.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6094
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 41238.19
	Virtual memory used (MiB): 35638.81
	Swap memory total (MiB): 8521.18
	Swap memory used (MiB): 140.05
	Space in storage for jna.tmpdir (MiB): available: 143851.69, total: 475570.56
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 143851.69, total: 475570.56
	Space in storage for io.netty.native.workdir (MiB): available: 143851.69, total: 475570.56
	Space in storage for java.io.tmpdir (MiB): available: 143851.69, total: 475570.56
	Space in storage for workdir (MiB): available: 143851.69, total: 475570.56
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx24G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		betterf3: BetterF3 12.0.0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.6+e82f21f740
		cloth-config: Cloth Config v16 16.0.141
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.89
		durabilitytooltip: Durability Tooltip 1.1.5
		fabric-api: Fabric API 0.107.3+1.21.3
			fabric-api-base: Fabric API Base 0.4.49+fd37071f40
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.79+fd37071f40
			fabric-biome-api-v1: Fabric Biome API (v1) 14.0.6+fd37071f40
			fabric-block-api-v1: Fabric Block API (v1) 1.0.28+fd37071f40
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.16+fd37071f40
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.3+fd37071f40
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.23+fd37071f40
			fabric-command-api-v1: Fabric Command API (v1) 1.2.57+f71b366f40
			fabric-command-api-v2: Fabric Command API (v2) 2.2.36+fd37071f40
			fabric-commands-v0: Fabric Commands (v0) 0.2.74+df3654b340
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.6+fd37071f40
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.1+7f945d5b40
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.1+fd37071f40
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.3+fd37071f40
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.2.1+fd37071f40
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 21.0.15+fd37071f40
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.7+fd37071f40
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.7+825023f840
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 2.0.10+fd37071f40
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.59+fd37071f40
			fabric-item-api-v1: Fabric Item API (v1) 11.1.6+fd37071f40
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.16+fd37071f40
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.53+fd37071f40
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.51+df3654b340
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.4.0+fd37071f40
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.25+3f89f5a540
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.13+fd37071f40
			fabric-message-api-v1: Fabric Message API (v1) 6.0.20+fd37071f40
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 3.0.8+fd37071f40
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.4+fd37071f40
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 17.0.8+fd37071f40
			fabric-particles-v1: Fabric Particles (v1) 4.0.9+fd37071f40
			fabric-recipe-api-v1: Fabric Recipe API (v1) 7.0.3+fd37071f40
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.1+fd37071f40
			fabric-renderer-api-v1: Fabric Renderer API (v1) 4.0.4+fd37071f40
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.9.4+fd37071f40
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.54+73761d2e40
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.14+fd37071f40
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.82+df3654b340
			fabric-rendering-v1: Fabric Rendering (v1) 8.0.6+fd37071f40
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.8+fd37071f40
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.33+fd37071f40
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.99+fd37071f40
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.29+fd37071f40
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.1+fd37071f40
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.8+fd37071f40
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		iris: Iris 1.8.0-beta.8+mc1.21.3
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		itemscroller: Item Scroller 0.25.0-sakura.3
		java: OpenJDK 64-Bit Server VM 21
		journeymap: Journeymap 1.21.3-6.0.0-beta.29
			ar_com_hjg_pngj: pngj 2.1.0
			commonnetworking: Common Network 1.0.17-1.21.3
			journeymap-api-fabric: JourneyMap API 2.0.0-1.21.3-SNAPSHOT
		malilib: MaLiLib 0.22.0-sakura.5
		minecraft: Minecraft 1.21.3
		minihud: MiniHUD 0.33.0-sakura.5
		modmenu: Mod Menu 12.0.0-beta.1
		silk-all: Silk (All modules) 1.10.7
			silk-commands: Silk Commands 1.10.7
			silk-core: Silk Core 1.10.7
			silk-game: Silk Game 1.10.7
			silk-igui: Silk Inventory GUI 1.10.7
			silk-nbt: Silk NBT 1.10.7
			silk-network: Silk Network 1.10.7
			silk-persistence: Silk Persistence 1.10.7
		simplemagnets: Simple Magnets 1.1.12+a
		sodium: Sodium 0.6.0-beta.4+mc1.21.3
		sodium-extra: Sodium Extra 0.6.0-beta.4+mc1.21.3
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17+a
		tweakeroo: Tweakeroo 0.22.0-sakura.4
		universal-graves: Universal Graves 3.5.0+1.21.2
			common-protection-api: Common Protection API 1.0.0
			fabric-permissions-api-v0: fabric-permissions-api 0.3.2-SNAPSHOT
			placeholder-api: Placeholder API 2.5.0+1.21.2
			polymer-core: Polymer (Core) 0.10.0+1.21.2
				polymer-networking: Polymer (Networking) 0.10.0+1.21.2
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.10.0+1.21.2
			polymer-resource-pack: Polymer (Resource Pack) 0.10.0+1.21.2
				polymer-common: Polymer (Common) 0.10.0+1.21.2
			polymer-virtual-entity: Polymer (Virtual Entity) 0.10.0+1.21.2
			predicate-api: Predicate API 0.6.0+1.21.2
			server_translations_api: Server Translations API 2.4.0+1.21.2-rc1
				packet_tweaker: Packet Tweaker 0.6.0-pre.1+1.21.2-pre3
			sgui: sgui 1.7.1+1.21.2
		veinminer: Veinminer 2.2.0
			de_miraculixx_core: core 2.2.0
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.16.9-1.21.3
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 560.94, NVIDIA Corporation
	Window size: 2560x1440
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 16/16 chunks
	Resource Packs: vanilla, file/VanillaTweaks_r125377_MC1.21.x.zip, fabric, betterf3, cloth-config, durabilitytooltip (incompatible), fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, itemscroller, journeymap, malilib, minihud, modmenu, placeholder-api, polymer-core, polymer-resource-pack, silk-all, simplemagnets (incompatible), sodium, sodium-extra, supermartijn642corelib (incompatible), tweakeroo (incompatible), universal-graves, veinminer
	Current Language: en_us
	Locale: en_CA
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor `

**Comment by SuperMartijn642** [comment]
This has been fixed now in version 1.1.12b of Simple Magnets for Minecraft 1.20.5 - 1.21.3.
Thank you for reporting the issue!
