### ISSUE TITLE
[1.16.2] Magnets don't seem to respect PreventRemoteMovement item entity tag

### ISSUE THREAD

**Issue by WhitePhant0m** [SuperMartijn642/SimpleMagnets#7]
I tried using [demagnetize](https://www.curseforge.com/minecraft/mc-mods/demagnetize) mod to stop the magnet from pulling items in a specific area so it wouldn't mess up my automation that involves dropped items, but the magnet still pulled items even though the items should've not been pulled since they had PreventRemoteMovement NBT tag on the EntityItem.
![image](https://user-images.githubusercontent.com/33400200/92359734-6aa36100-f0f4-11ea-82ca-169684db7f32.png)
This image is from the demagnetize mod page.

**Comment by SuperMartijn642** [comment]
I added a check for the 'PreventRemoteMovement' tag now in version 1.0.7.

Thanks for the suggestion!
