### ISSUE TITLE
Project needs license

### ISSUE THREAD

**Issue by Sakata-MC** [SuperMartijn642/SimpleMagnets#8]
Just putting this here so you know that you really should get a license assigned to this project, with a license.txt file in the main folder of the repo.
You have the source available, but without a license, there is little to define legality, or intent. This is important if you have life happen, as it often does, and the project is temporarily or permanently abandoned.

**Comment by SuperMartijn642** [comment]
Thank you for the heads up, I added a LICENSE.txt to the main branch now.
